feat: updated to miniTDF conventions. Adapted test names accordingly
MannLabs/timsrust pull request #10
Opened 2023-11-03 11:04 UTC by sebastian-wehner-bruker

For the release of ProteoScape 2024 the naming conventions for miniTDF were changed to more accurately represent what the files contain. This updated naming convention is included in this PR for miniTDF spectrum reading. The test-file-names were also adapted accordingly.

2023-11-03 12:04 UTC, sander-willems-bruker requested changes

2023-11-03 12:05 UTC, sander-willems-bruker commented
We can consider doing some if these checks in file_format. For completeness, we should perhaps also enforce the existence of regular "analysis.tdf" and "_bin" files rather than just looking at the extension

2023-11-03 16:17 UTC, sebastian-wehner-bruker commented on src/file_readers/spectrum_readers/mini_tdf_reader.rs
> +        if filename.ends_with( std::format!("ms2spectrum.{}", extension).as_str()) {
no, the metadata file is called:  *.globalmetadata.parquet

2023-11-06 09:01 UTC, sebastian-wehner-bruker commented on src/file_readers/spectrum_readers/mini_tdf_reader.rs
> +    panic!("No '*.ms2spectrum.{}' file found in '{}'", extension, ms2_dir_path)
done. function is throwing an error now, which is unwrapped in the calling function.

2023-11-06 09:05 UTC, sebastian-wehner-bruker commented
I made a change in the function checking for file formats: As miniTDF does not have a defined extension for the parent directory (other than tdf, which has the ".d" extension). The assumption should be that the provided directory should either be a tdf or minitdf. No other file formats are supported for reading anyways. 
This is also super helpful for the ProteoScape workflow usecase, where no requirements for the directory name for miniTDF files are being made.

2023-11-06 15:09 UTC, merged